name: Build

on:
  workflow_run:
    workflows: ["Version Bump"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for Version Bumped Label
        id: check_label
        run: |
          # Fetch the labels for the PR associated with this workflow run
          LABELS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.workflow_run.pull_requests[0].number }}/labels | jq -r '.[].name')

          if echo "$LABELS" | grep -q "version-bumped"; then
            echo "Label 'version-bumped' found, proceeding with build."
          else
            echo "Label 'version-bumped' not found, exiting."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
