name: Check src Changes

on:
  pull_request:
    branches:
      - develop
      - release
      - main
  push:
    branches:
      - release

jobs:
  check-src-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is fetched for accurate diff comparison

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Determine base branch and set BASE_REF
        id: determine-base
        run: |
          # Set the base branch to the pull request's base branch or main as a fallback
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          else
            echo "BASE_REF=origin/main" >> $GITHUB_ENV
          fi

      - name: Compare src/ directory changes
        id: src-changes
        run: |
          # Use the BASE_REF determined from the previous step
          echo "Comparing changes with base branch: $BASE_REF"
          
          # Check for changes in the src directory
          if git diff --name-only "$BASE_REF"...HEAD | grep '^src/'; then
            echo "Changes found in src/ directory"
            echo "src_changes=true" >> $GITHUB_ENV
          else
            echo "No changes in src/ directory"
            echo "src_changes=false" >> $GITHUB_ENV
          fi

      - name: Fail if src/ has changes
        if: env.src_changes == 'true'
        run: |
          echo "This pull request includes changes in the src/ directory. Please ensure this complies with branch naming policies."
          exit 1
