name: Detect src/ Directory Changes

on:
  pull_request:
    branches:
      - develop
      - release
      - main
  push:
    branches:
      - release

jobs:
  detect-src-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is fetched for accurate diff comparison

      - name: Fetch base branch
        run: |
          # Fetch the base branch to ensure it's up-to-date
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - name: Identify changed files in src/ directory
        id: identify-changes
        run: |
          BASE_REF=origin/${{ github.event.pull_request.base.ref }}
          # List files in src/ that differ from the base branch
          CHANGED_FILES=$(git diff --name-only $BASE_REF...HEAD | grep '^src/')
          echo "changed_files<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Display revert commands
        if: env.changed_files != ''
        run: |
          echo "The following files in the src/ directory have been modified:"
          echo "${{ env.changed_files }}"
          echo ""
          echo "To revert these changes to their state in the base branch, you can run the following commands:"
          echo ""
          for file in ${{ env.changed_files }}; do
            echo "git checkout origin/${{ github.event.pull_request.base.ref }} -- $file"
          done
          echo ""
          echo "Please review these commands carefully before executing them to ensure you do not lose any important changes."
