name: Src Code Protection

on:
  pull_request:
    branches:
      - develop
      - release
      - main
  push:
    branches:
      - release

jobs:
  check-src-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is fetched for accurate diff comparison

      - name: Fetch the base branch
        run: |
          # Fetch only the specific base branch and update it locally
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}

      - name: Determine base branch and set BASE_REF
        id: determine-base
        run: |
          # Set the base branch to the pull request's base branch or main as a fallback
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BASE_REF=origin/${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          else
            echo "BASE_REF=origin/main" >> $GITHUB_ENV
          fi

      - name: Compare src/ directory changes
        id: src-changes
        run: |
          # Use the BASE_REF determined from the previous step
          echo "Comparing changes with base branch: $BASE_REF"
          
          # Check for changes in the src directory
          changed_files=$(git diff --name-only "$BASE_REF"...HEAD | grep '^src/')
          if [[ -n "$changed_files" ]]; then
            echo "Changes found in src/ directory:"
            echo "$changed_files"
            # Replace newline characters with a space for environment variable compatibility
            changed_files_single_line=$(echo "$changed_files" | tr '\n' ' ')
            echo "src_changes=true" >> $GITHUB_ENV
            echo "changed_files=$changed_files_single_line" >> $GITHUB_ENV
          else
            echo "No changes in src/ directory"
            echo "src_changes=false" >> $GITHUB_ENV
          fi

      - name: Fail if src/ has changes
        if: env.src_changes == 'true'
        run: |
          echo "This pull request includes changes in the src/ directory. The following files have been modified:"
          # Restore newline characters for display
          echo "${{ env.changed_files }}" | tr ' ' '\n'
          echo "Please ensure this complies with branch naming policies."
          exit 1
