name: Auto Version Bump on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm install

      - name: Bump version
        run: |
          # Perform the version bump (e.g., minor version increase)
          npm version minor

      - name: Commit and push version bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add package.json
          git commit -m "chore: bump version for PR"
          git push origin HEAD:${{ github.head_ref }} --force
