name: Auto Version Validation and Bump

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  validate-and-bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0  # Ensures the full history is fetched for accurate diffing

      - name: Fetch develop branch
        run: git fetch origin develop:develop

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current version from develop
        id: get_develop_version
        run: |
          git checkout develop
          develop_version=$(jq -r .version package.json)
          echo "develop_version=$develop_version" >> $GITHUB_ENV
          echo "Current version on develop: $develop_version"

      - name: Determine if branch name is valid
        id: validate_branch
        run: |
          branch_name="${{ github.head_ref }}"
          if [[ "$branch_name" =~ ^(feat|fix|hotfix|style|refactor|perf|test)/ ]]; then
            echo "Branch name is valid."
          else
            echo "Invalid branch name: $branch_name. Branch must start with one of feat/, fix/, hotfix/, style/, refactor/, perf/, or test/."
            exit 1
          fi

      - name: Verify PR label for version bump
        id: check_label
        run: |
          pr_number=${{ github.event.pull_request.number }}
          repo_full_name=${{ github.repository }}
          labels=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$repo_full_name/issues/$pr_number/labels")

          echo "Labels response: $labels"

          if echo "$labels" | jq empty; then
            label_names=$(echo "$labels" | jq -r '.[].name')
            version_labels=()
            while IFS= read -r label; do
              if [[ "$label" =~ ^version:\ (major|minor|patch)$ ]]; then
                version_labels+=("$label")
              fi
            done <<< "$label_names"

            if [ ${#version_labels[@]} -eq 0 ]; then
              echo "No valid version label found. Please add a label: version: major, version: minor, or version: patch."
              exit 1
            elif [ ${#version_labels[@]} -gt 1 ]; then
              echo "Multiple version labels found: ${version_labels[@]}. Please ensure only one version label is applied."
              exit 1
            else
              case "${version_labels[0]}" in
                "version: major")
                  bump_type="major"
                  ;;
                "version: minor")
                  bump_type="minor"
                  ;;
                "version: patch")
                  bump_type="patch"
                  ;;
              esac
              echo "bump_type=$bump_type" >> $GITHUB_ENV
            fi
          else
            echo "Failed to fetch labels or invalid JSON response."
            exit 1
          fi

      - name: Install dependencies
        run: npm install

      - name: Revert version bump if label changed
        if: ${{ env.bump_type != '' }}
        run: |
          git checkout ${{ github.head_ref }}
          current_version=$(jq -r .version package.json)
          if [ "$current_version" != "$develop_version" ]; then
            echo "Version in package.json ($current_version) differs from develop branch ($develop_version). Reverting to develop version."
            echo "$develop_version" | jq -R '{version: .}' > package.json
            git add package.json
            git commit -m "chore: revert version to match develop branch"
          else
            echo "Version in package.json matches develop branch. No revert needed."
          fi

      - name: Bump version with custom commit message
        if: ${{ env.bump_type != '' }}
        run: |
          git checkout ${{ github.head_ref }}
          old_version=$(jq -r .version package.json)
          npm version ${{ env.bump_type }} --no-git-tag-version
          new_version=$(jq -r .version package.json)
          git add package.json
          git commit -m "chore: bump version from $old_version to $new_version"

      - name: Push version bump commit
        if: ${{ env.bump_type != '' }}
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:${{ github.head_ref }}
